[package]

name = "alpaca"
version = "0.0.1"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]

[dependencies]
itertools = "*"
peg = "*"
simple_parallel = "*"
argparse = "*"

[dependencies.rust-htslib]
git = "https://github.com/christopher-schroeder/rust-htslib.git"
